package com.app.sakila.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;

@Schema(description = "Rental information returned for active rentals, history, and returns.")
public record RentalDTO(
    @Schema(example = "16050", description = "Rental identifier generated by the database.")
    Long id,

    @Schema(example = "ACADEMY DINOSAUR", description = "Real movie title from the Sakila database.")
    String filmTitle,

    @Schema(example = "2026-07-05T17:25:16", description = "Date and time when the movie was rented.")
    LocalDateTime rentalDate,

    @Schema(example = "null", description = "Date and time when the movie was returned. It is null while the rental is active. Example for a returned rental: 2022-08-30T01:51:46")
    LocalDateTime returnDate,

    @Schema(example = "ACTIVE", description = "Current rental status. Possible values: ACTIVE (not yet returned) or RETURNED (already returned).")
    String status
) {}
