package com.app.sakila.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;

@Schema(description = "Rental information returned for active rentals, history, and returns.")
public record RentalDTO(
    @Schema(example = "1", description = "Rental identifier generated by the database.")
    Long id,

    @Schema(example = "ACADEMY DINOSAUR", description = "Real movie title from the Sakila database.")
    String filmTitle,

    @Schema(example = "2026-06-24T10:30:00", description = "Date and time when the movie was rented.")
    LocalDateTime rentalDate,

    @Schema(example = "2026-06-26T16:45:00", description = "Date and time when the movie was returned. It is null while the rental is active.")
    LocalDateTime returnDate,

    @Schema(example = "RETURNED", description = "Current rental status. Example values: RENTED or RETURNED.")
    String status
) {}
